AN-1251_silver staking objects
FlipsideCrypto/osmosis-models pull request #23
Opened 2022-05-20 18:23 UTC by eric-laurello

- delegate, redelegate, undelegate, withdraw rewards working as expected with current data
    - superfluid staking rewards that include two assets are broken into two lines

-  superfluid delegate, lock and delegate, undelegate excluded for v1 due to missing information around the amount and validator contained in the tx body.

2022-05-20 18:52 UTC, desmond-hui requested changes

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +            ) = 'superfluid_unbond_underlying_lock' THEN 'superfluid_unbond_underlying_lock'
I am a bit confused by this case section in conjunction w/ the where clause where we are specifically ignoring these values.  Can you elaborate?

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +        END AS event_Type
this should be `event_type` all lowercase

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +        A._Ingested_at,
this should be `_ingested_at` all lowercase

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +        ) b
I don't think this subquery is necessary.  Cleaner to just join to base on the existing join keys.  If there are conflicting column names in your select, just choose which one you want by having an alias

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +        )
do an inner join instead of subquery.  In general subqueries are slower

2022-05-20 18:52 UTC, desmond-hui commented on models/silver/silver__staking.sql
> +),
You may want to consider having a higher level CTE where `msg_attributes` is pre-filtered to A) only have the date range you need and B) only have the msg_type and/or attribute_key you need in the rest of the model

2022-05-20 19:08 UTC, eric-laurello commented on models/silver/silver__staking.sql
> +            ) = 'superfluid_unbond_underlying_lock' THEN 'superfluid_unbond_underlying_lock'
They are only hard-coded excluded for now until we implement the superfluid stuff. I wanted to just keep them in the code for now, but if you prefer we remove it I can save off a copy.

2022-05-24 17:31 UTC, desmond-hui requested changes

2022-05-24 17:38 UTC, desmond-hui approved these changes

2022-05-24 17:39 UTC, merged