An 1431 osmosis balances
FlipsideCrypto/osmosis-models pull request #55
Opened 2022-07-21 17:46 UTC by jhuhnke

2022-07-22 18:39 UTC, desmond-hui requested changes
Can't run staked balances model.  It is referencing `ingested_at` instead of `_inserted_timestamp`.  

Looks like this also needs to be updated from main because other models arent up to date

2022-07-22 18:52 UTC, desmond-hui requested changes

2022-07-22 18:52 UTC, desmond-hui commented on models/silver/silver__daily_balances.sql
> +),
I think this part is causing it so that a `--full-refresh` cannot be run

18:50:46  Completed with 1 error and 0 warnings:
18:50:46  
18:50:46  Database Error in model silver__daily_balances (models/silver/silver__daily_balances.sql)
18:50:46    002003 (42S02): SQL compilation error:
18:50:46    Object 'OSMOSIS_DEV.SILVER.DAILY_BALANCES' does not exist or not authorized.
18:50:46    compiled SQL at target/run/osmosis_models/models/silver/silver__daily_balances.sql

2022-07-22 20:07 UTC, desmond-hui submitted a review, later dismissed
Doesn't look like the model is handling 0 balances.  For instance...my wallet should not have any `gamm/pool/1` tokens.

The bronze data shows the last block_id where I had tokens for that pool and then subsequently it is no longer returned by the API because I superfluid staked them.

`select *
from osmosis.bronze.balances_api
where address = 'osmo1fv0sg786x94w9xsg0vna3rlyer2mg9eclgvmwe'
and block_id in (4355168,4419980)
order by block_id;`

however the daily balances data still shows I have the tokens

`SELECT *
FROM osmosis_dev.silver.daily_balances
WHERE address = 'osmo1fv0sg786x94w9xsg0vna3rlyer2mg9eclgvmwe'
and balance_type = 'liquid'
and currency = 'gamm/pool/1'
order by currency, date;`

2022-10-07 19:04 UTC, eric-laurello approved these changes

2022-10-07 19:06 UTC, merged