AN-1074 (1075 & 1076) Initial push of silver txn tables
FlipsideCrypto/osmosis-models pull request #6
Opened 2022-04-27 17:45 UTC by eric-laurello

2022-04-27 18:50 UTC, desmond-hui requested changes

2022-04-27 18:50 UTC, desmond-hui commented on models/silver/silver__msgs.sql
> +  cluster_by = ['block_timestamp::DATE'],
This should be clustered by `ingested_at::date`

2022-04-27 18:50 UTC, desmond-hui commented on models/silver/silver__msgs.sql
> +    -- outer => TRUE
remove commented out code

2022-04-27 18:50 UTC, desmond-hui commented on models/silver/silver__msg_attributes.sql
> +    ) AS xValue,
use something like `decoded_value` `decoded_key` is a bit more descriptive.  Also lets be consistent with casing.  We use all lower case with `_` between works.  So this should at least be `x_value` and `x_key`

2022-04-27 18:50 UTC, desmond-hui commented on models/silver/silver__msg_attributes.sql
> +  base A pivot(MAX(xvalue) for xKey IN ('key', 'value')) AS p (
what are you trying to achieve with `MAX(xvalue)`?  Do you have a sample tx_id where this is utilized?

2022-04-27 18:56 UTC, eric-laurello commented on models/silver/silver__msg_attributes.sql
> +  base A pivot(MAX(xvalue) for xKey IN ('key', 'value')) AS p (
I thought for the pivot you need some sort of an aggregate function. I'm just trying to get the two rows of data into two columns.

2022-04-27 18:56 UTC, eric-laurello commented on models/silver/silver__msg_attributes.sql
> +    ) AS xValue,
makes sense, will update.

2022-04-27 23:45 UTC, desmond-hui commented
@eric-laurello are these failures expected?

`Failure in test silver__blocks__block_id-assert_no_gap (tests/silver/silver__blocks__block_id-assert_no_gap.sql)
23:43:45    Got 26 results, configured to fail if != 0
23:43:45  
23:43:45    compiled SQL at target/compiled/osmosis_models/tests/silver/silver__blocks__block_id-assert_no_gap.sql
23:43:45  
23:43:45  Failure in test silver__transactions__tx-gap (tests/silver/silver__transactions__tx-gap.sql)
23:43:45    Got 101 results, configured to fail if != 0
23:43:45  
23:43:45    compiled SQL at target/compiled/osmosis_models/tests/silver/silver__transactions__tx-gap.sql`

2022-04-28 15:04 UTC, desmond-hui approved these changes

2022-04-28 15:06 UTC, merged