AN-2245 superfluid staked balances
FlipsideCrypto/osmosis-models pull request #64
Opened 2022-10-20 15:11 UTC by eric-laurello

2022-10-20 20:41 UTC, desmond-hui requested changes
Add `.DS_Store` to `.gitignore`

2022-10-20 20:41 UTC, desmond-hui commented on models/silver/silver__locked_liquidity_actions.sql
> +            WHEN j :"lock_tokens--duration" IS NOT NULL THEN 'inital lock'
typo for the value

2022-10-20 20:41 UTC, desmond-hui commented on models/silver/silver__locked_liquidity_balances.sql
> +) }}
Add business logic output testing 

see: https://github.com/FlipsideCrypto/solana-models/blob/56d024d15592dabe5a657c699322d2ceaafac699/models/silver/nfts/silver__nft_mints.yml#L11

2022-10-21 13:27 UTC, eric-laurello commented
@desmond-hui requested changes applied

2022-10-21 17:18 UTC, desmond-hui approved these changes

2022-10-21 17:18 UTC, merged