AN-2381 tx count macro and silver table
FlipsideCrypto/osmosis-models pull request #70
Opened 2022-11-09 16:49 UTC by eric-laurello

2022-11-09 17:02 UTC, desmond-hui requested changes

2022-11-09 17:02 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +  ethereum.streamline.udf_api(
This should be calling the JSON RPC udf

2022-11-09 17:02 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +    ),{ 'Authorization':(
Using REST call does not take advantage of JRPC batching capabilities

2022-11-09 23:32 UTC, desmond-hui requested changes

2022-11-09 23:32 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +    'https://osmosis-coke.allthatnode.com:56657',{ 'Authorization':(
`'Authorization'` should be `x-allthatnode-api-key`

2022-11-09 23:32 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +  ) AS resp,
This logic does not batch requests and is still sending 50 requests separately.  We should be able to batch all 50 into a single UDF call

2022-11-10 14:41 UTC, eric-laurello commented on macros/snowflake_api/get_blockchain_api.sql
> +  ) AS resp,
So that's what I was mentioning yesterday. The new UDF does accept the array so I can group the 50(or more) into one call, but I'm getting an internal service error when calling it. 

How can I troubleshoot that further? Looked in cloudwatch and do not see a log for this api.

2022-11-11 19:43 UTC, desmond-hui requested changes

2022-11-11 19:43 UTC, desmond-hui commented on models/silver/silver__blockchain.yml
> +
Even though we are using a merge strategy, I still think we should add a primary key check

2022-11-11 19:43 UTC, desmond-hui commented on models/silver/silver__blockchain.sql
> +        _inserted_timestamp
I think we should rename these to match existing conventions.  It is confusing to have block_id mean something else in this table vs. what is in `silver.blocks`

2022-11-11 19:43 UTC, desmond-hui commented on models/silver/silver__blockchain.sql
> +        _inserted_timestamp
Do we need to parse out all this data or should we just leave most of it in the raw json and expose that as a column?

2022-11-11 19:43 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +    'https://osmosis-coke.allthatnode.com:56657/',{ 'headers':{ 'x-allthatnode-api-key':(
You can remove the `headers` object

2022-11-11 19:43 UTC, desmond-hui commented on macros/snowflake_api/get_blockchain_api.sql
> +    ) }},{ 'data' :call }
you can remove the `data` wrapper, latest PR will accept the array

2022-11-11 22:22 UTC, desmond-hui approved these changes

2022-11-14 16:08 UTC, merged